branch-defaults:
  default:
    environment: edu-env-dev
    group_suffix: null
  main:
    environment: edu-env-dev
global:
  application_name: edu_env
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
